5u21対応
Fintan-contents/nablarch-training pull request #7
Opened 2022-04-20 04:47 UTC by h2irano

- Nablarchの適用バージョンを5u19→5u21に変更
- 上記バージョンアップに伴いテスト実装をJUnit5に対応（handson-08は適用外とする）

2022-04-22 00:48 UTC, developer-mkh requested changes

2022-04-22 00:48 UTC, developer-mkh commented on entity/pom.xml
> +        <version>5u21</version>
ハンズオン教材としてのバージョンが上がってないですね。
（7行目のversionタグ）
他も同様かと思いますので、横並びでお願いします。

2022-04-22 00:48 UTC, developer-mkh commented on nablarch-handson-app-web/src/test/java/com/nablarch/example/app/web/action/AuthenticationActionRequestTest.java
> +import com.nablarch.example.app.test.ExampleHttpRequestTest;
このクラスがソースに含まれていないようのですが・・・。
他のリクエスト単体系も同様です。

2022-04-22 00:51 UTC, developer-mkh requested changes
このコメント欄は無視してください（GitHubのレビュー操作間違えてしまって・・・。）

2022-04-22 00:53 UTC, developer-mkh approved these changes

2022-04-22 00:54 UTC, developer-mkh requested changes
他に以下ご対応下さい。
- 各ハンズオンのreadmeが参照しているNablarch解説書のバージョンが5u19になっています。
  - LATESTにしていないのは、Nablarchのバージョンアップとハンズオンのバージョンアップのタイミングがが完全に同期していないためです。
- history.mdもアップデートください。

2022-04-25 08:27 UTC, h2irano commented on nablarch-handson-app-web/src/test/java/com/nablarch/example/app/web/action/AuthenticationActionRequestTest.java
> +import com.nablarch.example.app.test.ExampleHttpRequestTest;
こちらはcommit漏れのため追加しました。

2022-04-25 08:29 UTC, h2irano commented on entity/pom.xml
> +        <version>5u21</version>
トレーニングコンテンツのバージョンを上げました。
また、history.mdにも履歴を追記しています。

2022-04-25 08:32 UTC, h2irano commented
> 



> 他に以下ご対応下さい。
> 
> * 各ハンズオンのreadmeが参照しているNablarch解説書のバージョンが5u19になっています。
>   
>   * LATESTにしていないのは、Nablarchのバージョンアップとハンズオンのバージョンアップのタイミングがが完全に同期していないためです。
> * history.mdもアップデートください。

Nablarch5u21のドキュメントへ参照先を更新しました。
history.mdもコンテンツのバージョニング更新とあわせて対応済です。

2022-04-25 09:05 UTC, developer-mkh commented on entity/pom.xml
> +        <version>5u21</version>
以下2つの依存関係について、1.5.0のままですね。
```
    <dependency>
      <groupId>nablarch.handson</groupId>
      <artifactId>nablarch-handson-app-entity</artifactId>
      <version>1.5.0</version>
    </dependency>
```
```
    <dependency>
      <groupId>nablarch.handson</groupId>
      <artifactId>nablarch-handson-app-web-common</artifactId>
      <version>1.5.0</version>
    </dependency>
```

2022-04-25 09:12 UTC, developer-mkh commented on nablarch-handson-app-web/src/test/java/com/nablarch/example/app/web/action/AuthenticationActionRequestTest.java
> +import com.nablarch.example.app.test.ExampleHttpRequestTest;
テストは実行されるようになったのですが、アップロードのリクエスト単体がエラーになってしまいました。
テストレポートを貼っておきます。
```
  <testcase name="uploadNormal" classname="com.nablarch.example.app.web.action.ProjectUploadActionRequestTest" time="0.245">
    <failure message="uploadNormal_Shot1_ファイルアップロード[HTTP STATUS] expected:&lt;[2]00&gt; but was:&lt;[4]00&gt;" type="org.junit.ComparisonFailure"><![CDATA[org.junit.ComparisonFailure: uploadNormal_Shot1_ファイルアップロード[HTTP STATUS] expected:<[2]00> but was:<[4]00>
	at com.nablarch.example.app.web.action.ProjectUploadActionRequestTest.uploadNormal(ProjectUploadActionRequestTest.java:30)
]]></failure>
    <system-out><![CDATA[2022-04-25 18:08:35.750 -INFO- HTTP_ACCESS [202204251808357490043] boot_proc = [] proc_sys = [] req_id = [/action/projectUpload/upload] usr_id = [999999999] @@@@ BEGIN @@@@ rid = [/action/projectUpload/upload] uid = [999999999] sid = [node0514ybgh87poq8a5k13zpexsa42]
	url         = [http://127.0.0.1/action/projectUpload/upload]
	method      = [POST]
	port        = [80]
	client_ip   = [0.0.0.0]
	client_host = [0.0.0.0]
2022-04-25 18:08:35.750 -INFO- HTTP_ACCESS [202204251808357490043] boot_proc = [] proc_sys = [] req_id = [/action/projectUpload/upload] usr_id = [999999999] @@@@ PARAMETERS @@@@
	parameters  = [{
		uploadFile = [uploadNormal.csv],
		nablarch_token = [d8348591-679b-46a9-a8e0-d51ccc0f005a]}]
2022-04-25 18:08:35.759 -INFO- HTTP_ACCESS [202204251808357490043] boot_proc = [] proc_sys = [] req_id = [/action/projectUpload/upload] usr_id = [999999999] @@@@ END @@@@ rid = [/action/projectUpload/upload] uid = [999999999] sid = [node0514ybgh87poq8a5k13zpexsa42] url = [http://127.0.0.1/action/projectUpload/upload] method = [POST] status_code = [400] content_path = [servlet:///WEB-INF/view/projectUpload/create.jsp]
	start_time     = [2022-04-25 18:08:35.750]
	end_time       = [2022-04-25 18:08:35.759]
	execution_time = [9]
	max_memory     = [4198498304]
	free_memory    = [4107608128]
]]></system-out>
  </testcase>
  <testcase name="uploadAbNormal" classname="com.nablarch.example.app.web.action.ProjectUploadActionRequestTest" time="0.051">
    <failure message="uploadAbNormal_Shot1_バリデーションエラー発生 different element(s) found. expected has [errors.upload.validate], actual has [errors.upload.format].  expected:&lt;[errors.upload.[validate]]&gt; but was:&lt;[errors.upload.[format]]&gt;" type="org.junit.ComparisonFailure">org.junit.ComparisonFailure: uploadAbNormal_Shot1_バリデーションエラー発生 different element(s) found. expected has [errors.upload.validate], actual has [errors.upload.format].  expected:&lt;[errors.upload.[validate]]&gt; but was:&lt;[errors.upload.[format]]&gt;	at com.nablarch.example.app.web.action.ProjectUploadActionRequestTest.uploadAbNormal(ProjectUploadActionRequestTest.java:38)</failure>
    <system-out><![CDATA[2022-04-25 18:08:35.882 -INFO- HTTP_ACCESS [202204251808358820044] boot_proc = [] proc_sys = [] req_id = [/action/projectUpload/upload] usr_id = [999999999] @@@@ BEGIN @@@@ rid = [/action/projectUpload/upload] uid = [999999999] sid = [node0ywh7i1hrdu6e17lau6oj4eud343]
	url         = [http://127.0.0.1/action/projectUpload/upload]
	method      = [POST]
	port        = [80]
	client_ip   = [0.0.0.0]
	client_host = [0.0.0.0]
2022-04-25 18:08:35.883 -INFO- HTTP_ACCESS [202204251808358820044] boot_proc = [] proc_sys = [] req_id = [/action/projectUpload/upload] usr_id = [999999999] @@@@ PARAMETERS @@@@
	parameters  = [{
		uploadFile = [uploadAbNormal.csv],
		nablarch_token = [cde33659-30ca-49b4-bb64-eccb2dbb70c8]}]
2022-04-25 18:08:35.885 -INFO- HTTP_ACCESS [202204251808358820044] boot_proc = [] proc_sys = [] req_id = [/action/projectUpload/upload] usr_id = [999999999] @@@@ END @@@@ rid = [/action/projectUpload/upload] uid = [999999999] sid = [node0ywh7i1hrdu6e17lau6oj4eud343] url = [http://127.0.0.1/action/projectUpload/upload] method = [POST] status_code = [400] content_path = [servlet:///WEB-INF/view/projectUpload/create.jsp]
	start_time     = [2022-04-25 18:08:35.882]
	end_time       = [2022-04-25 18:08:35.885]
	execution_time = [3]
	max_memory     = [4198498304]
	free_memory    = [4087685184]
]]></system-out>
  </testcase>
  <testcase name="indexNormal" classname="com.nablarch.example.app.web.action.ProjectUploadActionRequestTest" time="0.044"/>
</testsuite>
```

2022-04-25 09:45 UTC, developer-mkh approved these changes

2022-04-25 09:46 UTC, merged